diff --git a/Makefile.am b/Makefile.am
index c581aed..c5004c8 100755
--- a/Makefile.am
+++ b/Makefile.am
@@ -6,7 +6,7 @@ if HAVE_WEBSOCKETS
 mod_LTLIBRARIES = mod_whisper.la
 mod_whisper_la_SOURCES  = mod_whisper.c websock_glue.c
 mod_whisper_la_CFLAGS   = $(AM_CFLAGS) $(WEBSOCKETS_CFLAGS) $(KS_CFLAGS)
-mod_whisper_la_LIBADD   = $(switch_builddir)/libfreeswitch.la $(KS_LIBS)
-mod_whisper_la_LDFLAGS  = -avoid-version -module -no-undefined -shared $(WEBSOCKETS_LIBS)
+mod_whisper_la_LIBADD   = $(switch_builddir)/libfreeswitch.la $(KS_LIBS) $(WEBSOCKETS_LIBS)
+mod_whisper_la_LDFLAGS  = -avoid-version -module -no-undefined -shared 
 endif
 endif
