applications/mod_commands
applications/mod_conference

applications/mod_db

applications/mod_dptools
applications/mod_hash
applications/mod_httapi
applications/mod_spandsp

codecs/mod_b64
codecs/mod_g729
codecs/mod_opus

databases/mod_pgsql

dialplans/mod_dialplan_xml

endpoints/mod_loopback

endpoints/mod_rtc

endpoints/mod_skinny
endpoints/mod_sofia
endpoints/mod_verto
endpoints/mod_h323
event_handlers/mod_event_socket

formats/mod_local_stream
formats/mod_native_file
formats/mod_sndfile
formats/mod_tone_stream

languages/mod_lua

loggers/mod_console

loggers/mod_logfile
loggers/mod_syslog

